### ISSUE TITLE
Clear button on 0.11 dashboard

### ISSUE THREAD

**Issue by xMAnton** [graknlabs/grakn#1153]
Hi,

The Clear button on the new dashboard removes the query box content only. It doesn't clean out the graph anymore, and the console output neither.

I don't know if it is the desired behaviour now.

Tested on OSX 10.11.6 with Safari 10.0.3 and Chrome 56.0.2924.87.

**Comment by fppt** [comment]
Hi xMAnton,

That was actually a design decision on our part. We thought it would be best to not allow you to clear the graph too easily because you could do so accidentally.

However, the functionality is still there, all you have to do is to Shift click on the button and that will clear the graph.

A help window is in the works which should help you get used to the new dashboard.

Let us know if there is anything else you need.

**Comment by xMAnton** [comment]
It's ok then.

Thank you, Filipe

Antonio
