### ISSUE TITLE
[GUI] does not redraw the graph if I decrease limit

### ISSUE THREAD

**Issue by pouledodue** [graknlabs/grakn#1492]
UI/dashboard does not redraw the graph if I decrease limit

Reproduce:
-----------------------------------
1) load the UI in browser 0.0.0.0:4567
2) `match $p isa concept; limit 100;` <---- here the UI shows 100 things (it is OK)
3) change the query for `match $p isa concept; limit 1;` <---- here I expect the vizualization to be redrawn to show only 1 concept but it keeps the previous 100 in the view, so I need to `CMD-R` to reload the webpage to get rid of the previous 100;

**Comment by marco-scoppetta** [comment]
Hi @pouledodue ,
thanks again for the feedback. 

The one described in this issue is an expected behaviour, all the queries executed from the Graql editor will **add** nodes/edges to the graph (unless they are already drawn).

Keep in mind that also `offset` is an important parameter to set if you want to ask for the same concept types in different queries.

 Example: 
 - say you execute `match $x isa concept; limit 2;` (in this case offset will be set to 0 by default) -> and you get two concepts `A` and `B`.
- now you will have 2 nodes in your graph
- if you now execute `match $x isa concept; limit 1;` offset will be still set to 0 by default, so you will get `A` as a result
- your graph won't change in this case because `A` is already drawn in the visualiser.

In your case you could try `match $x isa person; offset 100; limit 1;` and you will see how 1 node will be added to the graph.

This being said, I will soon add a button that will allow to easily clear the canvas if the current graph in not needed anymore. In the meantime you can either refresh the page or `ctrl+click` on empty canvas and then move the mouse to start drawing a selecting rectangle on the canvas. So you can select all the nodes you don't need anymore. Once they are all selected you can `shift+right-click` on one of them to delete them all from the visualiser.

I hope this helps,
let us know if you have new suggestions / issues,

thank you!

Marco

**Comment by pouledodue** [comment]
Maybe just add the word "add" somewhere would suffice ...

![screenshot](https://cloud.githubusercontent.com/assets/745437/25497524/e052d2ac-2b52-11e7-8ba8-c85ac40f6fd7.png)

The 'add' functionnality is great though;
