### ISSUE TITLE
Test failures building the source in Windows .

### ISSUE THREAD

**Issue by th3iedkid** [graknlabs/grakn#1854]
Noticed test failures for GraqlShellTest , esp due to using UNIX style paths for the scripts.
These appear fixable, however would like to understand better ,If there is anything specific that might prevent anyone from building in Windows ?

**Comment by burukuru** [comment]
Hi @th3iedkid!

Unfortunately we currently don't have support for Windows due to Cassandra 2.1 not being fully compatible with Windows ([see our wiki](https://grakn.ai/pages/documentation/resources/grakn-on-windows.html)).
We also don't have a Windows environment to test in nor will the startup scripts work.

I'll check with our developers to see if the stack might have any issues building/running on Windows otherwise.

**Comment by fppt** [comment]
Hi @th3iedkid,

We don't officially support windows yet but it is possible to run the stack on windows. You will have to manually setup a running instance of cassandra and then modify the [engine configs](https://github.com/graknlabs/grakn/blob/master/conf/main/grakn.properties) to connect to that cassandra. You will have to do the same for Redis.

**Comment by th3iedkid** [comment]
Hi ,

Thanks, yes  I was just trying to use it as a dev rig of sorts, to build the code on windows and run it from IDE(IntelliJ).

I kind of got the npm’s generating in the build part , however there are tests esp ones related to Cassandra-unit that seem to fail .
I shall get back with more info on the changes towards getting it build on windows over the weekend.
