### ISSUE TITLE
Assigning an existing attribute to a newly inserted entity throws an "INVALID_ARGUMENT: GraqlQueryException-cannot overwrite properties " error

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4088]
_This issue was originally posted by @lolski  on 2018-07-17 15:16_.

Error observed in `1.3.0-SNAPSHOT` (commit `867551594eec4e86cf35272ee9837401aa3cbc71`) and `1.2.0` Reproduce: 
```
define name sub attribute datatype string;
define person sub entity has name;
commit;
insert isa name "John"; // or in 1.2.0: insert isa name val "John";
match $x isa name "John"; insert isa person has name $x; // or in 1.2.0: match $x isa name val "John"; insert isa person has name $x; 
commit;
```
 The same error is thrown by the following variants: 
```
 match $x isa name "John"; insert $p isa person has name $x; 
```

**Comment by flyingsilverfin** [comment]
Results of initial investigation:

This fails because we the RHS (insert) boils down to an `insert a person` and `insert $x isa name`, the latter of which already exists on the LHS (match). 

This can be solved partially in a hacky way by modifying `QueryOperationExecutor.insertAll`  (variant ` insertAll(Collection<VarPatternAdmin> patterns, GraknTx graph, ConceptMap results, QueryPlannerStatistic queryPlannerStatistic)`) to read:

```
return create(patterns.stream().filter(p -> !results.containsVar(p.admin().var())).collect(Collectors.toSet()), graph, ExecutionType.INSERT, queryPlannerStatistic).insertAll(results);
```

However, this short term solution may not be appropriate/be placed somewhere else, and now would not throw when things like `match $x isa thing; insert $x isa person` are written.

More interestingly, this opens up a further discussion on how certain edge cases such as 
`match $x isa person; insert $x isa person` should behave (fail loudly, or do nothing silently? With the above filter it would fail silently). Additionally, how to handle previously mentioned cases such as upcasts/downcasts (`match $x isa person; insert $x isa animal`, where person < animal).

I think general agreement is these are more or less nonsensical (esp considering an entity can only have one 'isa' edge), but requires discussion on what behavior should happen.

@kasper-piskorski  @lolski

**Comment by sorsaffari** [comment]
**Similar query leading to the same error:**

Grakn version: 1.4.2

## Expected outcome:
```
>>> $ match $p id V90296 has last-name $ln; insert $np isa person has last-name $ln;
{$np id V28848 isa person;}
```

## Actual outcome
```
>>> $ match $p id V90296 has last-name $ln; insert $np isa person has last-name $ln;
INVALID_ARGUMENT: GraqlQueryException-cannot overwrite properties `$ln isa last-name` on  concept `Base Type [ATTRIBUTE] - Id [V28848] - Value [Lilywhite] `. Please check server logs for the stack trace.
```
