### ISSUE TITLE
Redisq: where did it go?

### ISSUE THREAD

**Issue by 3lix** [graknlabs/grakn#4377]
Hello, recently I think you deleted the redisq project that you had encouraged people to adopt https://blog.grakn.ai/redisq-an-easy-to-use-reliable-java-library-for-asynchronous-messaging-in-redis-28a6905a5ce3
I am trying to understand the reasons it was removed? and if you are going to maintain it moving forward. 
Thanks in advance

**Comment by 3lix** [comment]
Sounds good, thanks for the reply.
We started using redisq on a new project that's not released so we haven't really been able to assess the technology in a prod env.

I would really appreciate if you could share with me the reasons you migrated from it. Specifically, any ```stability``` (bugs) or ```performance``` issues ? 
Thanks.

**Comment by marco-scoppetta** [comment]
There is nothing wrong with RedisQ, it was working just fine for us. 

We migrated from it simply because we changed the way we are implementing post-processing on attributes (which was the reason why we needed a redis queue).
We also wanted to reduce the number of running processes when starting Grakn, removing Redis we moved from 3 processes to 2.

**Comment by 3lix** [comment]
Thanks for the insights @marco-scoppetta
