### ISSUE TITLE
Load.sh script in the academy does not work with windows power shell (win10)

### ISSUE THREAD

**Issue by kristall** [graknlabs/grakn#4453]
The script load.sh in academy-master.zip\academy-master\short-training does not work with the windows power shell (win10).

What did work? I unzipped the academy-master als academy into the grakn folder where I also start the grakn. In change into that folder with the wps (windows power shell) and then call
`.\graql console -f .\academy\short-training\schema.gql -k academy`
to load the ontology and the rest follows that way.

So the creating of the $Vars did not really work, so I did it by hand, since I not that firm with the wps myself (I normally use linux too) but  maybe a bat file for windows might be a good solution.

**Comment by marco-scoppetta** [comment]
@kristall have you tried running `.\graql console -f .\academy\short-training\schema.gql -k academy` using the normal CMD in windows? so that `graql.bat` file should be used. That usually works for us, we have never tested it with the powershell yet, we will start some testing on it. In the meantime let us know if it works the `graql.bat` file, thanks

**Comment by kristall** [comment]
A window pops up saying that the files couldn't be found. So my guess would be that the path lines in the first 4 lines of the script had some issue. And since the window went away after trying I needed to add a read statement to be actually able to read what the problem was.

**Comment by marco-scoppetta** [comment]
Great, we'll fix that very soon,

thank you for reporting!

**Comment by marco-scoppetta** [comment]
Closing this as we won't support Academy anymore.
