### ISSUE TITLE
Change `grakn-core server start` to be `grakn start`

### ISSUE THREAD

**Issue by marco-scoppetta** [graknlabs/grakn#4490]

**Comment by haikalpribadi** [comment]
Yes, let's rename `grakn-core` back to `grakn`. And I'm still in the agreement with the idea of making the command shorter to `grakn start`, but I just want to share more thoughts on this.

First, there is a lack of "symmetry" because:
- `grakn start` starts the `server` WITH the keyword _"start"_, and WITHOUT the keyword _"server"_, but 
- `grakn console` starts the `console` WITHOUT the keyword _"start"_, and WITH the keyword _"console"_.

I think the confusion is because `grakn start` makes it appear to the user that keyword `grakn` represent the "program". And if the user only installs `grakn-core-server` or `grakn-core-console` (or any standalone module in the future), the user can only do one of the following but not the other: 
- `grakn start` but not `grakn console`
- `grakn console` but not `grakn start`.
And here it makes it a bit more confusing, because the above commands make lesser sense individually.

But if we keep the old way, it is also still confusing
- `grakn server [start|stop]` will start/stop the server, but
- `grakn console` does not need the keyword `start` to start the console

I don't have a solution to all the above yet, just sharing them here. For now, `grakn start` and `grakn console` is still the best option we got. cc: @marco-scoppetta @lolski

**Comment by sorsaffari** [comment]
@haikalpribadi @marco-scoppetta @lolski  what about this guys?

**Server**
to start: `grakn server` starts the server and continues to display server logs as transactions take place.

to stop: `ctrl + c` on the same terminal window in which the `grakn server` was run 👆.
in case the `grakn server` terminal window has already been closed, the user can run `grakn server` (again) in a new terminal window, which would display the logs for the server that's already running. then `ctrl + c` to stop the server.

**Console**
to start: `grakn console`
to stop: `exit`

**Comment by haikalpribadi** [comment]
What if you run Grakn by doing `grakn server &`, how do you terminate the server, @sorsaffari ?

**Comment by sorsaffari** [comment]
Well, if we want to provide a command that terminates the server that's running in the background then we'd have to go back to having `grakn server stop`. Otherwise and if we require the server to be running in foreground before it can be terminated then it'd go like so:
1. `grakn server &`
2. `grakn server`
3. `ctrl + c`

**Comment by haikalpribadi** [comment]
So the summary of our discussion is that:
1. Running `grakn server` in the foreground is unexpected for servers, and leaving it running in the foreground is also error-prone and dangerous in production environments.
2. The fact that we want two separate distributions for `grakn-core-server` and `grakn-core-console` creates the expectations to the users that they are 2 separate _"programs_". If running one _"program"_ (console) requires you to name the program in the command (`grakn console`), it's also expected that running other programs (server) should also use the name in the command (`grakn server start`)
3. Because the console is a foreground application and server is a background application, we are okay the distinction of running console by `grakn console` and running/stopping server with the keyword `start`/`stop` by `grakn server [start|stop]`
4. We agree that we don't like the verbosity of `grakn-core ...` or `grakn-kgms ...` as the shell command. We can now remove `-core` or `-kgms`, because: by making sure that the package managers (maven, aptitude, brew, etc) create a subfolder for Grakn Core and KGMS separately (`grakn/core/...` and `grakn/kgms/...`) we can let the user to have both distributions installed, and have the `grakn` command sitting in `/usr/bin/grakn` or `/usr/local/bin/grakn` to be a symlink to point to either one of the distributions and will be configurable.

I will now take on this issue and rename `grakn-core` to `grakn` where it's used across the codebase.

cc: @marco-scoppetta @lolski @sorsaffari
