### ISSUE TITLE
Migration shell scripts and independent cassandra

### ISSUE THREAD

**Issue by drchriskirk** [graknlabs/grakn#4621]
Hi and great progress in a short time.

I'm not seeing example migration scripts (for linux... csv to cassandra etc) anymore.  Have they been moved or am I not in line with progress and should be using another method?

I find it hard to see how to start grakn 'without' cassandra with the current java only subscripting.  I accept the move away from shell scripts but see no flexibility anymore.  I have in mind a situation where (for example in 0.15) one could start 'easily' using a grakn-engine script...thus enabling an existing cassandra instance to be running in parallel with grakn...both sharing the same keyspaces by editing cassandra.yaml.

Could you kindly consider this matter or point me to a directory or configuration that might resolve my dilemma?

Many thanks

**Comment by haikalpribadi** [comment]
Hi @drchriskirk ! Good to see you in our community again :)

1) I'm not sure what you mean by "CSV to Cassandra", but this sounds like a question/disussion, rather than a GitHub issue (feature/bug). Would you mind posting it again on https://discuss.grakn.ai ? Sorry for the trouble, but I thought you'd get more/better resopnses on the right platform. :)

2) I'm sorry that what I'm about to tell you is not documented (we'll fix that), but you can start Grakn's Engine and Cassandra separately, actually. (This syntax is valid in v1.4.2)
- `./grakn server start` starts the full Grakn (engine & storage)
- `./grakn server start engine` just starts Engine
- `./grakn server start storage` just starts Cassandra

I hope that helps!
