### ISSUE TITLE
Attribute nodes that are deleted don't show up again on shift + double click

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/grakn#4710]
Grakn version: 1.5 Snapshot

## Reproducing steps:
1. visualise some `thing` that is expected to own attributes
2. select the node for that 'thing'
3. hold shift and double click on it
4. right click on one of the attributes (that were just shown)
5. delete it
6. repeat 2 and 3

## Expected outcome:
the attribute that previously deleted should show again

## Actual outcome
the attribute that previously deleted doesn't show anymore

**Comment by Irtazaraza** [comment]
This is a known issue regarding the offset of loading neighbours or attributes of a node. Since we are retrieving the attributes using a query with an offset and limit. It is not possible to know which iteration of attribute was deleted in order to recover it. 

This is a very specific use-case which we can over look for now. The way around will be to re-query for that 'thing' to reset the offset of neighbours or attributes.
