### ISSUE TITLE
After cleaning the keyspace, the console doesn't get back into the interactive mode

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/grakn#4957]
Grakn version: 1.5 SNAPSHOT

```
./grakn console -k test
test> clean
test> confirm
```

## Expected outcome:
```
Keyspace deleted: test
test>
```

## Actual outcome
```
Keyspace deleted: test
```
... and nothing more.

**Comment by marco-scoppetta** [comment]
@sorsaffari this is intentional for the time being, and this is because if we were to delete a keyspace and then immediately re-open a transaction to that same keyspace we would immediately re-create it.
So for now if you delete a keyspace you should just exit the console. There is another issue related to defining the behaviour of "cleaning" VS "deleting" from console vs "cleaning" the whole Grakn: https://github.com/graknlabs/grakn/issues/3904
