### ISSUE TITLE
Subclasses of AttributeTypeImpl 'put' and 'get' are not overridden, and may produce incorrect outcomes

### ISSUE THREAD

**Issue by alexjpwalker** [graknlabs/grakn#5907]
## Description

AttributeTypeImpl.Boolean.'put' and 'get' are not overridden, and may produce incorrect outcomes.

We should ensure that 'put' throws a ROOT_TYPE_MUTATION error and 'get' returns null immediately.

**Comment by haikalpribadi** [comment]
Actually, this is not a bug. I was about to implement what was suggested above, and found that the reason we do not override `put()` and `get()` methods of `AttributeTypeImpl`.

For `put()`, the reason is because every method to create instances through concept API, such as `EntityTypeImpl.create()` or `AttributeTypeImp.Boolean.put()` always start by calling `TypeImpl.validateIsCommittedAndnotAbstract()`: https://github.com/graknlabs/grakn/blob/3bc0d56b5bcb447fe487065d641ab6bee327fe75/concept/type/impl/TypeImpl.java#L152-L158

Because of that, overriding `put()` in `AttributeTypeImple.XXX.Root()` is redundant, as the validation method above already catches for that case. Also, `ROOT_TYPE_MUTATION` would not be the right exception to throw (in which all the methods overridden in `.Root` classes do), because `AttributeTypeImpl.XXX.Root.put()` would not be "modifying" the type. It would only be creating an instance for an "abstract" type and should be throwing `ILLEGAL_ABSTRACT_WRITE` error.

For `get()` we don't need to override as well as the main behaviour already covers the behaviour of calling `get()` on root types: it will return null.
