### ISSUE TITLE
Cannot subtype an attribute type unless it is abstract

### ISSUE THREAD

**Issue by DiligentDilettante** [graknlabs/grakn#6250]
In [the current documentation](https://dev.docs.grakn.ai/docs/schema/concepts#subtype-an-attribute), an example is given for subtyping of attributes. The example given fails.

``` graql
define

event-date sub attribute,
    value datetime;
birth-date sub event-date;
start-date sub event-date;
end-date sub event-date;
```
Executing this query results in `Invalid Type Write: The attribute type 'event-date' cannot be subtyped as it is not abstract. Please check server logs for the stack trace.`

The following section ("[define an abstract attribute](https://dev.docs.grakn.ai/docs/schema/concepts#define-an-abstract-attribute)") succeeds, and furthermore it works when it is subtyped.
``` graql
define

event-date sub attribute, abstract,
    value datetime;
birth-date sub event-date;
start-date sub event-date;
end-date sub event-date;
```

Entities and Relations can still be subtyped whether abstract or not.

If this is the correct behavior the documentation should be updated. Otherwise, this might be a bug.

**Comment by DiligentDilettante** [comment]
I can think of a lot of times, however, that it would be useful to have non-abstract attributes which are subtyped. One example I had previously working was `uri` subtyped by `canonical-uri` and `archive-uri` indicating a location in general vs a canonical uri being the canonical location of a thing and an archive being a location where it had been archived, so if there's a decision to be made whether to change the behavior I do like the old way of being able to have non-abstract attributes with subtypes.

**Comment by DiligentDilettante** [comment]
It appears this changed in this commit: https://github.com/VladGan/grakn/commit/f343942d140a2856e5fb5ef89b9e8b3c1e22fe49#diff-3d250a9ed0168df375031ffe4dab5f1321db7caa3568c5285ea71fb49abf2996R109 which has been there since 2020-07-05, so there may indeed be a technical reason this relatively new limitation is in place, though why it's not limiting entities or relations I'm not sure. The documentation may just need updating.

**Comment by haikalpribadi** [comment]
Thanks for raising this issue, @DiligentDilettante! I should have explained it clearly in this release notes, but I seem to have forgotten. This was a critical change we introduced in Grakn 2.0.

Indeed, you cannot subtype an attribute type that is not abstract. There is a deliberate reason for this restriction.

In the new Grakn 2.0, we have defined the semantics of an `attribute` to be uniquely defined by its `type` (attribute type) and its `value`. I.e. given an attribute `type` and `value`, you can immediately uniquely identify an `attribute` concept. Making `attribute`s fundamentally [_"immutable"_](https://en.wikipedia.org/wiki/Immutable_object). There is a strong motivation as to why we defined the semantics of attributes in this way: to make attribute ownership queryable as patterns. The challenge is in performance. And the consequence is in the modelling philosophy. Let me try to explain the three points further below. (And add them to our docs).

1) The motivation: querying attribute ownerships as a pattern

By defining attributes to be uniquely defined by their type and value, we can make sure there's only one instance of that attribute in the entire database, in which all things may be connected to. For example if there is a person with the name "bob", and a company with the name "bob", you can easily query for these two things by writing:
```
match 
$x isa person, has name $n;
$y isa company has name "$n;
```
The query above will return the person and company with the name "bob". This behaviour makes attributes to form connections between things as a graph that you can now query.

2) The challenge: performance of writing and reading attributes

By defining attributes to be uniquely defined by their type and value, we make attributes very efficient to read and write in Grakn 2.0, as they all have the same byte representation and takes up one position in the storage space. Attributes can be inserted and reinserted, without creating duplicate copies of themselves in the storage as they always take up the same position. They can also be deleted at once, even when multiple inserts of the same attribute values has happened.

3) The consequence: philosophical restriction in modelling attributes

If we are to define attributes to be uniquely defined by their type and value, then we cannot allow non-abstract attribute types to have subtypes. If a non-abstract attribute type has a (non-abstract) type, then there can exist two attributes with the same value, where one attribute's type is the super type of the other. This would violate the semantic definition of an attribute as we defined above, as there will be 2 distinct attributes with the same value and can be interpreted to have the same type. For example, if you have 2 attribute types - `name` and `first-name`, where each of them have an attribute instance with value `"bob", you will then have 2 instances of `name:"bob"` because the second instance "first-name:"bob"` can be interpreted as `name:"bob"`. This is a clash in the logical semantics.

I hope that explains the behaviour. I'll make sure to update this into our documentation.

**Comment by haikalpribadi** [comment]
I've updated the schema example in the docs now, @DiligentDilettante
